# Generated by Django 4.1.7 on 2023-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=160)),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_sent', models.DateTimeField()),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
